CREATE TRIGGER Staff_Training_Insert_TR
ON STAFF_TRAINING
INSTEAD OF INSERT
AS
DECLARE @COURSE_FK int
DECLARE @COURSE_FSK int

DECLARE @SATISFACTION_FK int
DECLARE @SATISFACTION_FSK int
DECLARE @SATISFACTION_YEAR int
DECLARE @SATISFACTION_STAFF_CODE int

DECLARE @TIMESTAMP date

SELECT @COURSE_FK = COURSE_CODE_FK FROM INSERTED
SELECT @SATISFACTION_FK = SATISFACTION_TYPE_CODE_FK FROM INSERTED
SELECT @TIMESTAMP = GETDATE()--TIMESTAMP FROM INSERTED
SELECT @SATISFACTION_YEAR = YEAR_PK from INSERTED
SELECT @SATISFACTION_STAFF_CODE = SALES_STAFF_CODE_PK FROM INSERTED

SELECT @COURSE_FSK = (SELECT top(1) ID_SK FROM COURSE 
        WHERE COURSE.COURSE_CODE_FK = @COURSE_FK
        AND COURSE.TIMESTAMP < @TIMESTAMP
        ORDER BY COURSE.TIMESTAMP DESC)


SELECT @SATISFACTION_FSK = (SELECT top(1) ID_SK FROM SATISFACTION
        WHERE SATISFACTION.YEAR_PK = @SATISFACTION_YEAR
        AND SATISFACTION.SALES_STAFF_CODE = @SATISFACTION_STAFF_CODE
        AND SATISFACTION.TIMESTAMP < @TIMESTAMP
        ORDER BY SATISFACTION.TIMESTAMP DESC)


BEGIN
	----INSERT INTO STAFF_TRAINING
	----	(YEAR_PK, 
	----	SALES_STAFF_CODE_PK,
	----	FULL_NAME,
	----	POSITION_EN,
	----	COURSE_CODE_FK,
	----	COURSE_CODE_FSK,
	----	SATISFACTION_TYPE_CODE_FK,
	----	SATISFACTION_TYPE_CODE_FSK)
	----SELECT 
	----	YEAR_PK,
	----	SALES_STAFF_CODE_PK,
	----	FULL_NAME,
	----	POSITION_EN
	----	COURSE_CODE_FK,
	----	@COURSE_FSK,
	----	SATISFACTION_TYPE_CODE_FK, 
	----	@SATISFACTION_FSK
	----FROM INSERTED

	--SELECT * FROM INSERTED
	--PRINT 'Test'

	SELECT @COURSE_FSK, @SATISFACTION_FSK, @COURSE_FK, @SATISFACTION_FK


END

-- BREAKLINE

SELECT top(10) * FROM SATISFACTION 
WHERE SATISFACTION.TIMESTAMP < getdate()
ORDER BY SATISFACTION.TIMESTAMP DESC;

SELECT * FROM STAFF_TRAINING 
ORDER BY STAFF_TRAINING.TIMESTAMP DESC

PRINT CAST(getdate() AS DATE);

INSERT INTO STAFF_TRAINING
(YEAR_PK, SALES_STAFF_CODE_PK,FULL_NAME,POSITION_EN,COURSE_CODE_FK,SATISFACTION_TYPE_CODE_FK)
VALUES(2004, 100,'Tuomas, Savolainen','Level 2 Sales Representative	',2, 1)

use GreatOutdoorsDW

SELECT top(1) ID_SK FROM COURSE 
        WHERE COURSE.COURSE_CODE_FK = 4
        AND COURSE.TIMESTAMP < GETDATE()
        ORDER BY COURSE.TIMESTAMP DESC


SELECT * FROM COURSE