-- INSERT INTO PRODUCT
INSERT INTO PRODUCT
	(PRODUCT_NUMBER_PK, INTRODUCTION_DATE,PRODUCT_TYPE_CODE, PRODUCT_TYPE_EN,
	 PRODUCT_LINE_CODE,PRODUCT_LINE_EN,PRODUCTION_COST,MARGIN,
	 PRODUCT_IMAGE,PRODUCT_NAME,PRODUCT_DESCRIPTION_EN,LANUGAGE) 
VALUES 
	(1, '2011-02-15 00:00:00', 1, 'Cooking Gear', 1, 'Camping Equipment' ,
	4.0, 0.33, 'P01CE1CG1.jpg', 'TrailChef Water Bag', 
	'Lightweight, collapsible bag to carry liquids easily.  Wide mouth for easy filling.  Holds 10 liters.', 'EN' 
)


INSERT INTO SATISFACTION
  (YEAR, SALES_STAFF_CODE, SATISFACTION_TYPE_CODE, SATISFACTION_TYPE_DESCRIPTION)
VALUES(2004,100,1,'Not satisfied')


INSERT INTO STAFF_TRAINING
(YEAR_PK, SALES_STAFF_CODE_PK,FULL_NAME,POSITION_EN,COURSE_CODE_FK,SATISFACTION_TYPE_CODE_FK)
VALUES(2004, 100,'Tuomas, Savolainen','Level 2 Sales Representative	',2, 1)

INSERT INTO ORDER_DETAILS(ORDER_NUMBER_PK,ORDER_DETAIL_CODE_PK,ORDER_DETAILS_QUANTITY,  ORDER_DETAILS_UNIT_COST,ORDER_DETAILS_UNIT_PRICE, ORDER_DETAILS_UNIT_SALE_PRICE,    ORDER_DETAILS_DISCOUNT_PERCENTAGE,ORDER_DETAILS_TURNOVER,ORDER_DETAILS_PROFIT,ORDER_DATE,SALES_BRANCH_CODE_FK,RETAILER_SITE_CODE,RETAILER_SITE_CONTACT)VALUES(9479,110948,144,2.0,7.0,5.75,82.14,828.0,540.0,'2022-02-02 00:00:00',15,338,329)



