-- INSERT INTO PRODUCT
INSERT INTO PRODUCT
	(PRODUCT_NUMBER_PK, INTRODUCTION_DATE,PRODUCT_TYPE_CODE, PRODUCT_TYPE_EN,
	 PRODUCT_LINE_CODE,PRODUCT_LINE_EN,PRODUCTION_COST,MARGIN,
	 PRODUCT_IMAGE,PRODUCT_NAME,PRODUCT_DESCRIPTION_EN,LANUGAGE) 
VALUES 
	(1, '2011-02-15 00:00:00', 1, 'Cooking Gear', 1, 'Camping Equipment' ,
	4.0, 0.33, 'P01CE1CG1.jpg', 'TrailChef Water Bag', 
	'Lightweight, collapsible bag to carry liquids easily.  Wide mouth for easy filling.  Holds 10 liters.', 'EN' 
)


INSERT INTO SATISFACTION
  (YEAR, SALES_STAFF_CODE, SATISFACTION_TYPE_CODE, SATISFACTION_TYPE_DESCRIPTION)
VALUES(2004,100,1,'Not satisfied')