--Dimensiewaardes

CREATE TABLE SALES_STAFF(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    SALES_STAFF_CODE_PK int,
    FIRST_NAME varchar,
    LAST_NAME varchar,
    FULL_NAME varchar,
    POSITION_EN varchar,
    WORK_PHONE varchar(50),
    EXTENSION int,
    FAX varchar,
    EMAIL varchar,
    DATE_HIRED date,
    SALES_BRANCH_CODE int FOREIGN KEY REFERENCES SALES_BRANCH(ID_SK),
    SALES_BRANCH_COUNTRY varchar,
    MANAGER_CODE int


);

CREATE TABLE SALES_BRANCH(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    SALES_BRANCH_CODE_PK int,
    ADDRESS1 varchar(200),
    ADDRESS2 varchar(200),
    POSTAL_ADDRESS varchar(200),
    COUNTRY varchar(200),
    REGION varchar(200),
    CITY varchar(200),
    POSTAL_ZONE varchar(50)
);





CREATE TABLE PRODUCT(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    PRODUCT_NUMBER_PK int,
    INTRODUCTION_DATE date,
    
    PRODUCT_TYPE_CODE int,
    PRODUCT_TYPE_EN varchar(200),

    PRODUCT_LINE_CODE int,
    PRODUCT_LINE_EN varchar(200),

    PRODUCTION_COST decimal(18,2),
    MARGIN decimal(4,2),
    PRODUCT_IMAGE varchar(200),
    PRODUCT_NAME varchar(200),
    PRODUCT_DESCRIPTION_EN varchar(1000),
    LANUGAGE varchar(100)
);

CREATE TABLE ORDER_METHOD(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    ORDER_METHOD_CODE int,
    ORDER_METHOD_EN varchar(200)
);




CREATE TABLE RETURN_REASON(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    RETURN_REASON_CODE int,
    RETURN_REASON_EN varchar(200)
);


-- samengesteld uit go_crm.Retailer_Contact, Retailer_Site, Retailer, 
--Retailer_Type, Country, Sales_Territory
CREATE TABLE RETAILER(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    RETAILER_SITE_CODE int,
    ADDRESS1 varchar(200),
    ADDRESS2 varchar(200),
    COUNTRY_CODE int,
    COOUNTRY_EN varchar(200),
    FLAG_IMAGE varchar(200),
    REGION varchar(200),
    CITY varchar(100),
    POSTAL_ZONE varchar(100),
    ACTIVE_INDICATOR int,

    SALES_TERRITORY_CODE int,
    TERRITORY_NAME_EN varchar(200),
    RETAILER_CODE int,
    RETAILER_CODEMR int,
    COMPANY_NAME varchar(200),

    RETAILER_TYPE_CODE int,
    RETAILER_TYPE_EN varchar(200),

    RETAILER_CONTACT_CODE int,
    FIRST_NAME varchar(200),
    LAST_NAME varchar(200),
    JOB_POSITION_EN varchar(200),
    EXTENSION int,
    FAX varchar(50),
    E_MAIL varchar(100),
    GENDER varchar(5)
);


CREATE TABLE COURSE(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    COURSE_CODE_FK int,
    DESCRIPTION varchar(200)
);



CREATE TABLE SATISFACTION(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    YEAR int,
    SALES_STAFF_CODE int,

    SATISFACTION_TYPE_CODE int,
    SATISFACTION_TYPE_DESCRIPTION varchar(100)
);

CREATE TABLE TIME(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    DATE_ID date, --Dit als primary key?
    YEAR int,
    MONTH int,
    DAY int
);

-- Feittabellen

CREATE TABLE Order_Details (
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

	ORDER_NUMBER_PK int,
	ORDER_DETAIL_CODE_PK int,
	ORDER_DETAILS_QUANTITY int,


	ORDER_DETAILS_UNIT_COST decimal(18,2),
	ORDER_DETAILS_UNIT_PRICE decimal(18,2),
	ORDER_DETAILS_UNIT_SALE_PRICE decimal(18,2),
	ORDER_DETAILS_DISCOUNT_PERCENTAGE decimal(5,2),
	ORDER_DETAILS_TURNOVER decimal(18,2),
	ORDER_DETAILS_PROFIT decimal(18,2),

	DAY_DATE date,
	SALES_BRANCH_CODE int,
	RETAILER_SITE_CODE int,
	RETAILER_SITE_CONTACT int
);


CREATE TABLE RETURNED_ITEM(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),


    RETURNED_ITEM_CODE_PK int,
    ORDER_DETAIL_CODE int,

    RETURN_DATE date,
    RETURN_QUANTITY int,

    RETURN_REASON varchar(250),
    PRODUCT_NUMBER int,
    PRODUCT_NUMBER_FSK int FOREIGN KEY REFERENCES PRODUCT(ID_SK) 
);


CREATE TABLE STAFF_TRAINING(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    Year_PK int,
    SALES_STAFF_CODE_PK int,

    FULL_NAME varchar(200),
    POSITION_EN varchar(200),

    COURSE_CODE_FSK int FOREIGN KEY REFERENCES COURSE(ID_SK),

    SATISFACTION_TYPE_CODE_FSK int FOREIGN KEY REFERENCES SATISFACTION(ID_SK),

);

CREATE TABLE GO_SALES_PRODUCT_FORECASTData(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    PRODUCT_NUMBER int,
    YEAR int,
    MONTH int,

    EXPECTED_VOLUME int 
);

CREATE TABLE GO_SALES_INVENTORY_LEVELSData(
    ID_SK int IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),

    INVENTORY_YEAR int,
    INVENTORY_MONTH int,
    PRODUCT_NUMBER int,

    INVENTORY_COUNT int 
);
